### ISSUE TITLE
NameError: uninitialized constant Sprockets::SassImporter

### ISSUE THREAD

**Issue by MarkMurphy** [vhyza/sass-rails-source-maps#26]
```
$ rake assets:clobber
rake aborted!
NameError: uninitialized constant Sprockets::SassImporter
/Users/mark/.rvm/gems/ruby-2.1.2/gems/sass-rails-source-maps-0.1.0/lib/sass-rails-source-maps/sass_importer.rb:2:in `<module:SassRailsSourceMaps>'
/Users/mark/.rvm/gems/ruby-2.1.2/gems/sass-rails-source-maps-0.1.0/lib/sass-rails-source-maps/sass_importer.rb:1:in `<top (required)>'
/Users/mark/.rvm/gems/ruby-2.1.2/gems/sass-rails-source-maps-0.1.0/lib/sass-rails-source-maps.rb:5:in `<top (required)>'
/Users/mark/.rvm/gems/ruby-2.1.2/gems/bundler-1.10.6/lib/bundler/runtime.rb:76:in `require'
/Users/mark/.rvm/gems/ruby-2.1.2/gems/bundler-1.10.6/lib/bundler/runtime.rb:76:in `block (2 levels) in require'
/Users/mark/.rvm/gems/ruby-2.1.2/gems/bundler-1.10.6/lib/bundler/runtime.rb:72:in `each'
/Users/mark/.rvm/gems/ruby-2.1.2/gems/bundler-1.10.6/lib/bundler/runtime.rb:72:in `block in require'
/Users/mark/.rvm/gems/ruby-2.1.2/gems/bundler-1.10.6/lib/bundler/runtime.rb:61:in `each'
/Users/mark/.rvm/gems/ruby-2.1.2/gems/bundler-1.10.6/lib/bundler/runtime.rb:61:in `require'
/Users/mark/.rvm/gems/ruby-2.1.2/gems/bundler-1.10.6/lib/bundler.rb:134:in `require'
```

Rails 4.2.3
Using Sass Rails 5.0.4

**Comment by dechimp** [comment]
I am getting the same error after adding the gem.

**Comment by pdipietro** [comment]
Still getting the same error.

**Comment by jszwedko** [comment]
Me too, are there any workarounds?

**Comment by dechimp** [comment]
This might be a duplicate of #23
